# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_accounts_us.DataTable')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_accounts_us.Date')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=350)),
                ('unit', models.CharField(max_length=100)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_accounts_us.DataTable')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_accounts_us.Symbol'),
        ),
    ]
